---
- name: docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: yum-clean-metadata
  command: yum clean metadata

- name: install reqs
  yum:
    name:
      - device-mapper-persistent-data
      - lvm2
      - "{{docker_distrib}}"
    state: present

- name: enable docker
  service: name=docker enabled=yes state=started

- name: register var1 for docker-compose install
  shell: uname -s
  register: unames
  
- name: register var2 for docker-compose install
  shell: uname -m
  register: unamem


- name: docker_compose_install
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_ver }}/docker-compose-{{ unames.stdout }}-{{ unamem.stdout }}"
    dest: /usr/bin/docker-compose
    mode: 0755
