---
- name: Delete existing repo
  file:
    state: "{{ item }}"
    path: "/etc/yum.repos.d"
  with_items:
    - absent
    - directory 

- name: Centos Base
  yum_repository:
    name: centos
    description: Centos base repo
    baseurl: http://nexus/repository/centos7.6proxy-v2/os/$basearch

- name: Centos Updates
  yum_repository:
    name: centos-updates
    description: Centos Updates
    baseurl: http://nexus/repository/centos7.6proxy-v2/updates/$basearch

- name: Centos Extras
  yum_repository:
    name: centos-extras
    description: Centos Extras
    baseurl: http://nexus/repository/centos7.6proxy-v2/extras/$basearch

- name: Docker Repo
  yum_repository:
    name: docker-repo
    baseurl: http://nexus/repository/docker/centos/$releasever/$basearch/stable
    description: Docker CE Repo

- name: Epel
  yum_repository:
    name: epel
    baseurl: http://nexus/repository/epel76freeze
    description: Epel Freeze

- name: Gitlab Runner
  yum_repository:
    name: gitlab-runner
    baseurl: http://nexus/repository/gitlab-runner/el/$releasever/$basearch
    description: Gitlab Runner repo

- name: RPMFusionFree
  yum_repository:
    name: rpmfusion-free
    baseurl: http://nexus/repository/rpmfusion-free/$releasever/$basearch
    description: RpmFusion Free repo

- name: RPMFusionNonFree
  yum_repository:
    name: rpmfusion-nonfree
    baseurl: http://nexus/repository/rpmfusion-nonfree/$releasever/$basearch
    description: RpmFusion NonFree repo

- name: Iozone Repo
  yum_repository:
    name: iozone
    baseurl: http://nexus/repository/saltrpm/iozone/$basearch
    description: Iozone Repo

- name: Zabbix Repo
  yum_repository:
    name: zabbix
    baseurl: http://nexus/repository/zabbix42
    description: Zabbix Repo
